app/config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/landing_page'
  get 'static_pages/dashboard'
  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :municipes do
    collection do
      get :search
    end
    member do
      get :delete_foto_attached
    end
  end

  resources :enderecos do
    collection do
      get :search
    end
  end


  get :estados, controller: :brasil_api
  get :municipios, controller: :brasil_api
  get :cep, controller: :brasil_api
end

app/app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :municipe
  validates_presence_of :cep, :longr, :bairro, :cidade, :uf

  validates_length_of :cep, minimum: 8, maximum: 8
  validates_length_of :longr, minimum: 1, maximum: 50
  validates_length_of :complemento, minimum: 0, maximum: 50
  validates_length_of :bairro, minimum: 1, maximum: 80
  validates_length_of :cidade, minimum: 1, maximum: 30
  validates_length_of :uf, minimum: 2, maximum: 2
  validates_length_of :cdg_ibge, minimum: 0, maximum: 7

end

app/app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController
  before_action :set_endereco, only: %i[ show edit update destroy ]

  # GET /enderecos or /enderecos.json
  def index
    set_enderecos()
  end

  def search
    set_enderecos()
    if params[:term].present?
      @enderecos = @enderecos.like(params[:term])
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_enderecos()
    @enderecos = Endereco.all
  end

  def set_endereco()
    @endereco = Endereco.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def endereco_params
    params.require(:endereco).permit(:id, :cep, :longr, :complemento, :bairro, :cidade, :uf, :cdg_ibge, :municipe_id)
  end

end

app/app/views/enderecos/_table_endereco.html.erb
<table class="table table-bordered">
  <thead>
  <tr>

     <th><%= Utility.translate_attr(Endereco, :id) %></th>
     <th><%= Utility.translate_attr(Endereco, :cep) %></th>
     <th><%= Utility.translate_attr(Endereco, :longr) %></th>
     <th><%= Utility.translate_attr(Endereco, :complemento) %></th>
     <th><%= Utility.translate_attr(Endereco, :bairro) %></th>
     <th><%= Utility.translate_attr(Endereco, :cidade) %></th>
     <th><%= Utility.translate_attr(Endereco, :uf) %></th>
     <th><%= Utility.translate_attr(Endereco, :cdg_ibge) %></th>
     <th><%= Utility.translate_attr(Endereco, :municipe_id) %></th>
  </tr>
  </thead>
  <tbody>
  <% enderecos.each do |endereco| %>
    <tr>
      <td><%= Utility.translate_attr(Endereco, :id) %>: <%=endereco.id %></td>
      <td><%= Utility.translate_attr(Endereco, :cep) %>: <%=endereco.cep %></td>
      <td><%= Utility.translate_attr(Endereco, :longr) %>: <%=endereco.longr %></td>
      <td><%= Utility.translate_attr(Endereco, :complemento) %>: <%=endereco.complemento %></td>
      <td><%= Utility.translate_attr(Endereco, :bairro) %>: <%=endereco.bairro %></td>
      <td><%= Utility.translate_attr(Endereco, :cidade) %>: <%=endereco.cidade %></td>
      <td><%= Utility.translate_attr(Endereco, :uf) %>: <%=endereco.uf %></td>
      <td><%= Utility.translate_attr(Endereco, :cdg_ibge) %>: <%=endereco.cdg_ibge %></td>
      <td><%= Utility.translate_attr(Endereco, :municipe_id) %>: <%=endereco.municipe.nome %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/app/views/enderecos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= Utility.translate_attr(Endereco, :collection_name).to_s %></h1>

<div class="">
  <div class="">
    <%= form_with(url: search_enderecos_path, method: :get, id: 'form-search-endereco', remote: true) do |f| %>
      <%= f.text_field :term, class: 'form-control', id: 'search-endereco', placeholder: ". . ." %>
    <% end %>
  </div>

  <div id="enderecos-table" class="table-responsive m-2">
    <%= render 'table_endereco', enderecos: @enderecos %>
  </div>

</div>


<script>

    let searchField = $("#search-endereco")
    searchField.on('change', function (e) {
        $("#search-endereco").submit()
    });
</script>

app/app/views/enderecos/search.js.erb
alert('oie')