app/config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/landing_page'
  get 'static_pages/dashboard'
  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :municipes do
    collection do
      get :search
    end
    member do
      get :delete_foto_attached
    end
  end

  resources :enderecos do
    collection do
      get :search
    end
  end


  get :estados, controller: :brasil_api
  get :municipios, controller: :brasil_api
  get :cep, controller: :brasil_api
end

app/app/models/municipe.rb
class Municipe < ApplicationRecord

  has_one :endereco, dependent: :destroy
  has_one_attached :foto
  accepts_nested_attributes_for :endereco, reject_if: :all_blank

  validates_presence_of :nome, :cpf, :cns, :email, :dta_nasc, :telefone, :status ,:foto

  validates_length_of :nome, minimum: 1, maximum: 80
  validates_length_of :cpf, minimum: 11, maximum: 11
  validates_length_of :cns, minimum: 15, maximum: 15
  validates_length_of :email, minimum: 1, maximum: 256
  validates_length_of :telefone, minimum: 13, maximum: 13
  validate :validate_cpf, :validate_email, :validate_cns, :validate_nacimento

  enum status: { inactive: 0, active: 1 }
  scope :like, ->(term) {
    query = -> do
      qmunicipe = Municipe.columns.map(&:name).map { |attr| " CAST(#{Municipe.table_name}.#{attr} as varchar)  LIKE :term " }
      qendereco = Endereco.columns.map(&:name).map { |attr| "  CAST(#{Endereco.table_name}.#{attr} as varchar) LIKE :term " }
      "#{qmunicipe.join(" or ")} or #{ qendereco.join(" or ")}"
    end
    where(query.===, term: "%#{term}%")
  }

  def validate_cpf
    errors.add(:base, :invalid_cpf) unless Utility.cpf_is_valid?(cpf)
  end

  def validate_email
    errors.add(:base, :invalid_email) unless Utility.email_is_valid?(email)
  end

  def validate_cns
    errors.add(:base, :invalid_cns) unless Utility.cns_is_valid?(cns)
  end

  def validate_nacimento
    errors.add(:base, :invalid_birthday) unless Utility.nascimento_is_valid?(dta_nasc)
  end
end

app/app/controllers/municipes_controller.rb
class MunicipesController < ApplicationController
  before_action :set_municipe, only: %i[ show edit update destroy ]

  # GET /municipes or /municipes.json
  def index
    set_municipes()
  end

  def search
    set_municipes()

    if params[:term].present?
      @municipes = @municipes.like(params[:term])
    end
  end

  # GET /municipes/1 or /municipes/1.json
  def show
  end

  # GET /municipes/new
  def new
    @municipe = Municipe.new
    @municipe.build_endereco
  end

  # GET /municipes/1/edit
  def edit
    @municipe.build_endereco unless @municipe.endereco.present?
  end

  # POST /municipes or /municipes.json
  def create
    @municipe = Municipe.new(municipe_params)

    respond_to do |format|
      if @municipe.save
        create_deliver_info()
        set_municipes()
        format.html { redirect_to municipe_url(@municipe), notice: "Municipe was successfully created." }
        format.js { render 'municipes/create', notice: "Municipe was successfully created." }
        format.json { render :show, status: :created, location: @municipe }
      else
        @municipe.build_endereco if @municipe.endereco.blank?
        format.html { render :new, status: :unprocessable_entity }
        format.js { render 'municipes/create', status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_deliver_info
    begin
      attrs = @municipe.attributes.merge(@municipe&.endereco&.attributes&.to_h)
      MunicipeMailer.with(municipe: @municipe, attributes: attrs).new_municipe_email.deliver_now! if ::MAILER_PASSWORD.present?
      sms = Sms.new(attrs, @municipe.telefone, :create)
      sms.call
    rescue Exception => e

    end
  end

  def update_deliver_info
    begin
      changes = @municipe.saved_changes.merge(@municipe.endereco.saved_changes)
      MunicipeMailer.with(municipe: @municipe, changes: changes).update_municipe_email.deliver_now! if ::MAILER_PASSWORD.present?
      sms = Sms.new(changes, @municipe.telefone, :update)
      sms.call
    rescue Exception => e
      puts e.to_s
    end
  end

  # PATCH/PUT /municipes/1 or /municipes/1.json
  def update
    respond_to do |format|
      if @municipe.update(municipe_params)
        update_deliver_info()
        set_municipes()
        format.html { redirect_to municipe_url(@municipe), notice: "Municipe was successfully updated." }
        format.js { render 'municipes/update', notice: "Municipe was successfully updated." }
        format.json { render :show, status: :ok, location: @municipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.js { render 'municipes/update', status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /municipes/1 or /municipes/1.json
  def destroy
    @municipe.destroy

    respond_to do |format|
      format.html { redirect_to municipes_url, notice: "Municipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def delete_foto_attached
    @foto = ActiveStorage::Attachment.find(params[:foto_id])
    @foto.purge if @foto.present?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_municipes()
    @municipes = Municipe.eager_load(:endereco).order(created_at: :asc)
  end

  def set_municipe()
    @municipe = Municipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def municipe_params
    params.require(:municipe).permit(:nome, :cpf, :cns, :email, :dta_nasc, :telefone, :status, :foto,
                                     endereco_attributes: [:id, :cep, :longr, :complemento, :bairro, :cidade, :uf, :cdg_ibge, :municipe_id])
  end
end

app/app/views/municipes/_form.html.erb
<div>
  <%= form_with(model: municipe, html: { multipart: true }, data: { remote: true }, id: 'form-municipe') do |form| %>

    <div>
      <% if form.object.persisted? and form.object.foto.present? %>
        <div id='img-tag-div'>
          <div>
            <%= image_tag url_for(form.object.foto), height: "auto", width: "50px" %>
          </div>
          <%= link_to "X", delete_foto_attached_municipe_path(foto_id: form.object.foto.id), data: { confirm: Utility.translate_form(:confirm) }, remote: true %>
        </div>
      <% end %>
      <div id='foto-input-div'>
        <%= form.label :foto %>
        <%= form.file_field :foto, multiple: false %>
      </div>
    </div>

    <div>
      <%= form.label :nome, style: "display: block " %>
      <%= form.text_field :nome, class: 'form-control' %>
    </div>

    <div>
      <%= form.label :cpf, style: "display: block " %>
      <%= form.text_field :cpf, class: 'form-control' %>
    </div>

    <div>
      <%= form.label :cns, style: "display: block " %>
      <%= form.text_field :cns, class: 'form-control' %>
    </div>

    <div>
      <%= form.label :email, style: "display: block " %>
      <%= form.text_field :email, class: 'form-control' %>
    </div>

    <div>
      <%= form.label :dta_nasc, style: "display: block " %>
      <%= form.date_field :dta_nasc, class: 'form-control' %>
    </div>

    <div>
      <%= form.label :telefone, style: "display: block " %>
      <%= form.text_field :telefone, class: 'form-control' %>
    </div>

    <div>
      <%= form.label :status, style: "display: block " %>
      <%= form.select :status, options_for_enum(form.object, :statuses), {}, class: 'form-control' %>
    </div>

    <%= form.fields_for :endereco do |f| %>
      <% render 'endereco/endereco_fields', form: f %>
    <% end %>

    <div class="p-3">
      <%= form.submit Utility.translate_actions(Municipe, action_name.to_sym), class: 'btn-sm btn-primary' %>
    </div>
  <% end %>
</div>

<script>
    let setCepResponseData = function (data) {
        $("#cep").val(data['cep'])
        $("#uf").val(data['state'])
        $("#cidade").val(data['city'])
        getCidadeInfo(data['state'], {cidade: normalizeStr(data['city'])})
        $("#bairro").val(data['neighborhood'])
        $("#longr").val(data['street'])
    }
    let setEstadoResponseData = function (data, extra_data = null) {
        let select = $('#cidade');
        $(select).html("")
        $(data).each(function (index) {
            let name = capitalizeString(data[index]['nome'].toString())
            $(select).append(`<option value='${name}'> ${name} </option>`);
        });

        if (extra_data != null) {
            $(select).val(extra_data['cidade'])
        }
    }

    function getCepInfo(cep, extraData = null) {
        if (cep.length == 8) {
            ajaxGet("<%= cep_path %>", {cep: cep.toString()}, setCepResponseData)
        }
    }


    function getCidadeInfo(sigla_uf, extraData = null) {
        if (sigla_uf.length == 2) {
            ajaxGet("<%= municipios_path %>", {sigla_uf: sigla_uf.toString()}, setEstadoResponseData, null, extraData)
        }
    }


    function ajaxGet(url, params = null, sucessAction = null, failureAction = null, extraData = null) {
        $.getJSON(url, params, function (data) {
            sucessAction(data, extraData);
        }).done(function () {
            // console.log("second success");
        }).fail(function () {
            // console.log("error");
        }).always(function () {
            // console.log("complete");
        });
    }

    function capitalizeString(str) {
        return str.toString().toLowerCase().trim().replace(/^\w/, (c) => c.toUpperCase());
    }

    function normalizeStr(str) {
        return str.normalize('NFD').replace(/[\u0300-\u036f]/g, "");
    }
</script>

app/app/views/municipes/_municipe.html.erb
<div id="<%= dom_id municipe %>">
  <p>
    <strong>Nome:</strong>
    <%= municipe.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= municipe.cpf %>
  </p>

  <p>
    <strong>Cns:</strong>
    <%= municipe.cns %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= municipe.email %>
  </p>

  <p>
    <strong>Dta nasc:</strong>
    <%= municipe.dta_nasc %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= municipe.telefone %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= municipe.status %>
  </p>

</div>

app/app/views/municipes/_show.html.erb
<div>
  <h3><%= Utility.translate_class_name(Municipe) %></h3>
  <div class="rounded-5">
    <% if municipe.persisted? and municipe.foto.present? %>
      <div>
        <%= image_tag url_for(municipe.foto), height: "auto", width: "125px" %>
      </div>
    <% end %>
  </div>

  <ul class="list-group">
    <li class="list-group-item">
      <strong><%= Utility.translate_attr(municipe.class, :id) %> : </strong> <%= municipe.id %></li>
    <li class="list-group-item">
      <strong><%= Utility.translate_attr(municipe.class, :nome) %> : </strong> <%= municipe.nome %></li>
    <li class="list-group-item"><strong><%= Utility.translate_attr(municipe.class, :cpf) %> : </strong>
      <%= Utility.cpf_formatted(municipe.cpf) %>
    </li>
    <li class="list-group-item"><strong><%= Utility.translate_attr(municipe.class, :cns) %> : </strong>
      <%= Utility.cns_formatted(municipe.cns) %>
    </li>
    <li class="list-group-item">
      <strong><%= Utility.translate_attr(municipe.class, :email) %> : </strong> <%= municipe.email %></li>
    <li class="list-group-item">
      <strong><%= Utility.translate_attr(municipe.class, :dta_nasc) %>: </strong>
      <%= Utility.date_formatted(municipe.dta_nasc) %>
    </li>
    <li class="list-group-item"><strong><%= Utility.translate_attr(municipe.class, :telefone) %> : </strong>
      <%= Utility.phone_br_formatted(municipe.telefone) %>
    </li>
    <% if municipe.endereco.present? %>
      <div>
        <h3><%= Utility.translate_class_name(Endereco) %></h3>

        <ul>
          <li class="list-group-item"><strong><%= Utility.translate_attr(municipe.endereco.class, :id) %> : </strong>
            <%= municipe.endereco.id %>
          </li>
          <li class="list-group-item"><strong><%= Utility.translate_attr(municipe.endereco.class, :cep) %> : </strong>
            <%= Utility.cep_formatted(municipe.endereco.cep) %>
          </li>
          <li class="list-group-item"><strong><%= Utility.translate_attr(municipe.endereco.class, :longr) %> : </strong>
            <%= municipe.endereco.longr %>
          </li>
          <li class="list-group-item">
            <strong><%= Utility.translate_attr(municipe.endereco.class, :complemento) %> : </strong>
            <%= municipe.endereco.complemento %>
          </li>
          <li class="list-group-item">
            <strong><%= Utility.translate_attr(municipe.endereco.class, :bairro) %> : </strong>
            <%= municipe.endereco.bairro %>
          </li>
          <li class="list-group-item">
            <strong><%= Utility.translate_attr(municipe.endereco.class, :cidade) %> : </strong>
            <%= municipe.endereco.cidade %>
          </li>
          <li class="list-group-item"><strong><%= Utility.translate_attr(municipe.endereco.class, :uf) %> : </strong>
            <%= municipe.endereco.uf %>
          </li>
          <li class="list-group-item">
            <strong><%= Utility.translate_attr(municipe.endereco.class, :cdg_ibge) %> : </strong>
            <%= municipe.endereco.cdg_ibge %>
          </li>
          <li class="list-group-item">
            <strong><%= Utility.translate_attr(municipe.endereco.class, :municipe_id) %> : </strong>
            <%= municipe.endereco.municipe_id %>
          </li>
        </ul>
      </div>
    <% end %>
  </ul>

</div>

app/app/views/municipes/_table_municipe.html.erb
<table class="table table-bordered">
  <thead>
  <tr>
    <th><%= Utility.translate_attr(Municipe, :id) %></th>
    <th><%= Utility.translate_attr(Municipe, :nome) %></th>
    <th><%= Utility.translate_attr(Municipe, :cpf) %></th>
    <th><%= Utility.translate_attr(Municipe, :cns) %></th>
    <th><%= Utility.translate_attr(Municipe, :email) %></th>
    <th><%= Utility.translate_attr(Municipe, :dta_nasc) %></th>
    <th><%= Utility.translate_attr(Municipe, :telefone) %></th>
    <th><%= Utility.translate_attr(Municipe, :status) %></th>
    <th><%= Utility.translate_attr(Municipe, :action) %></th>
  </tr>
  </thead>
  <tbody>
  <% municipes.each do |municipe| %>
    <tr>
      <td><%= municipe.id %></td>
      <td><%= municipe.nome %></td>
      <td><%= Utility.cpf_formatted(municipe.cpf) %></td>
      <td><%= Utility.cns_formatted(municipe.cns) %></td>
      <td><%= municipe.email %></td>
      <td><%= Utility.date_formatted(municipe.dta_nasc) %></td>
      <td><%= Utility.phone_br_formatted(municipe.telefone) %></td>
      <td> <%= Utility.translate_enum_name(municipe.class.name, :statuses, municipe.status.to_sym) %></td>
      <td>
        <%= edit_btn(Municipe, edit_municipe_path(municipe), { remote: true }) if can?(:edit,Municipe) %>

        <%= show_btn(Municipe, municipe_path(municipe), { remote: true })  if can?(:read,Municipe) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/app/views/municipes/create.js.erb
<%= close_lg_modal(obj: @municipe) %>

<% unless @municipe.errors.present? %>
    $("#municipes-table").html("<%= j  render 'municipes/table_municipe', municipes: @municipes %>")
<%end %>

app/app/views/municipes/delete_foto_attached.js.erb
$("#img-tag-div").fadeOut()
$("#img-tag-div").html("")

app/app/views/municipes/edit.js.erb
<%= open_lg_modal('municipes/form',
 locals_variables:{
      municipe: @municipe
      },
 modal_options:{
       title: Utility.translate_actions(Municipe, :edit)
      }
 )
 %>

app/app/views/municipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= Utility.translate_attr(Municipe, :collection_name).to_s %></h1>

<div class="">
  <% if can?(:new, Municipe) %>
    <span class="pull-left m-2"><%= new_btn(Municipe, new_municipe_path, { remote: true }) %></span>
  <% end %>
  <div class="">
    <%= form_with(url: search_municipes_path, method: :get, id: 'form-search-municipe', remote: true) do |f| %>
      <%= f.text_field :term, class: 'form-control', id: 'search-municipe', placeholder: ". . ." %>
    <% end %>
  </div>

  <div id="municipes-table" class="table-responsive m-2">
    <%= render 'table_municipe', municipes: @municipes %>
  </div>

</div>


<script>

    let searchField = $("#search-municipe")
    searchField.on('change', function (e) {
        $("#search-municipe").submit()
    });
</script>

app/app/views/municipes/new.js.erb
<%= open_lg_modal('municipes/form',
 locals_variables:{
      municipe: @municipe
      },
 modal_options:{
       title: Utility.translate_actions(Municipe, :new)
      }
 )
 %>

app/app/views/municipes/search.js.erb
$("#municipes-table").html("<%= j  render 'table_municipe', municipes: @municipes %>")

app/app/views/municipes/show.js.erb
<%= open_lg_modal('municipes/show',
 locals_variables:{
      municipe: @municipe
      },
 modal_options:{
       title: Utility.translate_actions(Municipe, :show)
      }
 )
 %>

app/app/views/municipes/update.js.erb
<%= close_lg_modal(obj: @municipe) %>


<% unless @municipe.errors.present? %>
$("#municipes-table").html("<%= j  render 'municipes/table_municipe', municipes: @municipes %>")
<%end %>